version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_challenge
    restart: always
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: SenhaChallenge123
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_challenge
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fiap.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
