services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  app:
    build: .
    depends_on: [ db ]
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: challenge
      DB_USER: challenge
      DB_PASSWORD: challenge
    ports: ["8080:8080"]

volumes:
  pgdata:
