services:
  db:
    image: mysql:8.4
    container_name: fiap-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./_data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_PROFILE: mysql
    image: universidade-fiap:latest
    container_name: universidade-fiap
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "challenge"
      SPRING_DATASOURCE_PASSWORD: "challenge"
      PORT: "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: fiap-adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    restart: unless-stopped
