-- Ajusta default e NOT NULL para created_at (H2)
ALTER TABLE patio ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE patio ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

UPDATE patio SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

ALTER TABLE patio ALTER COLUMN created_at SET NOT NULL;
