-- Tabelas do projeto (somente domínio atual)

-- 1) Funções (roles)
CREATE TABLE IF NOT EXISTS funcao (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL UNIQUE
);

-- 2) Usuário do sistema
CREATE TABLE IF NOT EXISTS usuario (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL UNIQUE,
    senha        VARCHAR(255) NOT NULL,
    nome_perfil  VARCHAR(255),
    img_perfil   VARCHAR(255)
);

-- 3) Relação N:N usuário <-> função
CREATE TABLE IF NOT EXISTS usuario_funcao_tab (
    id_usuario BIGINT NOT NULL,
    id_funcao  BIGINT NOT NULL,
    PRIMARY KEY (id_usuario, id_funcao),
    CONSTRAINT fk_uf_usuario FOREIGN KEY (id_usuario) REFERENCES usuario (id),
    CONSTRAINT fk_uf_funcao  FOREIGN KEY (id_funcao)  REFERENCES funcao  (id)
);

-- 4) Pátio
CREATE TABLE IF NOT EXISTS patio (
    id_patio     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(60)  NOT NULL,
    localizacao  VARCHAR(120) NOT NULL,
    capacidade   INT          NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5) Status da Moto (catálogo)
CREATE TABLE IF NOT EXISTS status_moto (
    id_status_moto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(40) NOT NULL UNIQUE
);

-- 6) Sensor (pertence a um pátio)
CREATE TABLE IF NOT EXISTS sensor (
    id_sensor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo      VARCHAR(40) NOT NULL,
    status    VARCHAR(20) NOT NULL,
    pos_x     INT,
    pos_y     INT,
    id_patio  BIGINT NOT NULL,
    CONSTRAINT fk_sensor_patio FOREIGN KEY (id_patio) REFERENCES patio (id_patio)
);

-- 7) Moto (pertence a um pátio e tem um status)
CREATE TABLE IF NOT EXISTS moto (
    id_moto        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo         VARCHAR(50) NOT NULL,
    placa          VARCHAR(8)  NOT NULL UNIQUE,
    pos_x          INT,
    pos_y          INT,
    id_patio       BIGINT NOT NULL,
    id_status_moto BIGINT NOT NULL,
    CONSTRAINT fk_moto_patio  FOREIGN KEY (id_patio)       REFERENCES patio (id_patio),
    CONSTRAINT fk_moto_status FOREIGN KEY (id_status_moto) REFERENCES status_moto (id_status_moto)
);
