name: Build & Deploy to Azure Web App

on:
  push:
    branches: [ "master" ]   # troque para "main" se for o seu caso
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # ajuste o -Ppostgres se o seu pom usa outro profile (ou remova se não usa)
      - name: Build (Maven)
        run: mvn -Ppostgres -DskipTests package

      - name: Pick built JAR
        id: pick
        run: echo "jar=$(ls target/*-SNAPSHOT.jar | head -n1)" >> $GITHUB_OUTPUT

      # Garante que o site está como Java 17 (evita voltar para PHP)
      - name: Ensure Web App is Java 17
        run: |
          az webapp config set -g rg-fiap-2tdsph-sprint3-marcus-lucas -n java-challenge-s3-calazans --linux-fx-version "JAVA:17-java17"
          ID=$(az webapp show -g rg-fiap-2tdsph-sprint3-marcus-lucas -n java-challenge-s3-calazans --query id -o tsv)
          az resource update --ids "$ID" --set properties.siteConfig.metadata="[{'name':'CURRENT_STACK','value':'java'}]" properties.siteConfig.appCommandLine=""

      - name: Ensure App Settings
        run: |
          az webapp config appsettings set -g rg-fiap-2tdsph-sprint3-marcus-lucas -n java-challenge-s3-calazans --settings WEBSITES_PORT=8080 JAVA_OPTS="-Xms256m -Xmx512m"

      - name: Deploy JAR
        run: |
          az webapp deploy \
            -g rg-fiap-2tdsph-sprint3-marcus-lucas \
            -n java-challenge-s3-calazans \
            --type jar \
            --src-path "${{ steps.pick.outputs.jar }}"

      - name: Restart Web App
        run: az webapp restart -g rg-fiap-2tdsph-sprint3-marcus-lucas -n java-challenge-s3-calazans
