name: Build & Deploy to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AZ_RG: rg-fiap-sprint3-rm556620
      AZ_APP: java-challenge-s3-rm556620
      JAR_PATH: target/universidade_fiap-0.0.1-SNAPSHOT.jar

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (Maven, profile postgres)
        run: mvn -Ppostgres -DskipTests package

      # Garante CLI do Azure disponível para usar 'az'
      - name: Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            # (Opcional) Garantir runtime Java 17 — rodar só na 1ª vez
            az webapp config set -g "$AZ_RG" -n "$AZ_APP" --linux-fx-version "JAVA:17-java17"

            # (Opcional) Ajustes mínimos de app settings; já estão setados pelo script de infra
            az webapp config appsettings set \
              -g "$AZ_RG" -n "$AZ_APP" \
              --settings WEBSITES_PORT=8080 JAVA_OPTS="-Xms256m -Xmx512m"

            # Warm-up rápido do Kudu para evitar restart durante o deploy
            for i in {1..10}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" "https://$AZ_APP.scm.azurewebsites.net/")
              echo "SCM probe HTTP $code"
              [[ "$code" == "200" || "$code" == "401" ]] && break
              sleep 5
            done

            # Deploy do JAR
            az webapp deploy \
              -g "$AZ_RG" -n "$AZ_APP" \
              --type jar \
              --src-path "$JAR_PATH"
