name: Build & Deploy to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZ_RG: rg-fiap-sprint3-rm556620
      AZ_APP: java-challenge-s3-rm556620
      JAR_PATH: target/universidade_fiap-0.0.1-SNAPSHOT.jar

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build (Maven, profile postgres)
        run: mvn -Ppostgres -DskipTests package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Web App runtime & settings (first run safe)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config set -g "$AZ_RG" -n "$AZ_APP" --linux-fx-version "JAVA:17-java17"
            az webapp config appsettings set               -g "$AZ_RG" -n "$AZ_APP"               --settings WEBSITES_PORT=8080 JAVA_OPTS="-Xms256m -Xmx512m"

            # Warm up Kudu (optional)
            for i in {1..10}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" "https://$AZ_APP.scm.azurewebsites.net/")
              echo "SCM probe HTTP $code"
              [[ "$code" == "200" || "$code" == "401" ]] && break
              sleep 5
            done

      - name: Deploy JAR
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy               -g "$AZ_RG" -n "$AZ_APP"               --type jar               --src-path "$JAR_PATH"

      - name: Tail logs on failure
        if: failure()
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo '--- Last 200 lines of app logs ---'
            az webapp log tail -g "$AZ_RG" -n "$AZ_APP" --verbose &
            sleep 20
            pkill -f "az webapp log tail" || true
