name: Deploy to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Ajuste o perfil se necessário (seu pom tem o profile 'postgres')
      - name: Build (Maven)
        run: mvn -Ppostgres -DskipTests package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: java-challenge-s3-calazans
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4516EFC10A8E43578153F04FE4B9CD30 }}
          package: target/universidade_fiap-0.0.1-SNAPSHOT.jar
