name: Build & Deploy to Azure Web App (Publish Profile)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZ_APP: java-challenge-s3-rm556620
      JAR_PATH: target/universidade_fiap-0.0.1-SNAPSHOT.jar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build (Maven, profile postgres)
        run: mvn -Ppostgres -DskipTests package

      # Deploy usando Publish Profile (não requer azure/login)
      - name: Deploy with WebApps Deploy (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZ_APP }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BADA0C3698094B07A107CDBBB2E6EE4F }}
          package: ${{ env.JAR_PATH }}
