name: CI - Build & Test & Publish Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Build & Test
        run: mvn -B -ntp verify
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: mvn_version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:3.5.0:exec)" >> $GITHUB_OUTPUT
      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE:latest -t $IMAGE:${{ steps.mvn_version.outputs.VERSION }} .
      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker push $IMAGE:latest
          docker push $IMAGE:${{ steps.mvn_version.outputs.VERSION }}
