name: CI — Build, Test & Publish Image to GHCR

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      # Nome da imagem = ghcr.io/<owner>/<repo> (sempre minúsculo)
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test (Maven)
        run: |
          # Se seu projeto usa profile do Postgres, troque a linha abaixo por:
          # mvn -B -ntp -Ppostgres verify
          mvn -B -ntp verify

      # ------------ Docker buildx + metadata ------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta (labels & tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=sha
            type=ref,event=branch
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ github.repository }}

      - name: Lowercase image name (GHCR requires lowercase)
        id: img
        run: |
          echo "LOWER_IMAGE=${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cache de camadas de build
      - name: Configure cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build (no push on PRs)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.img.outputs.LOWER_IMAGE }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Move o cache novo para reutilizar no próximo run
      - name: Move build cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
