name: Build & Deploy to Azure Web App:java-challenge-s3-rm556620

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZ_APP: java-challenge-s3-rm556620
      # Se o nome do JAR variar, troque por: target/*.jar
      JAR_PATH: target/universidade_fiap-0.0.1-SNAPSHOT.jar

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (Maven, profile postgres)
        run: mvn -Ppostgres -DskipTests package

      - name: Deploy with WebApps Deploy (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZ_APP }}
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F90BE419CD704982876CBC9C36E45FF8 }}
          package: ${{ env.JAR_PATH }}
